# Use an OpenJDK 22 base image
FROM openjdk:22-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/efurniture-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your application will run on
EXPOSE 9090

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
